from __future__ import annotations

from pokergpu.core.betting import Chips
from pokergpu.tree.public_tree import ChildLink, InfosetId, NodeId, NodeType, PublicTree


def make_leduc_public_tree() -> PublicTree:
    return PublicTree(
        node_types=(
            NodeType.CHANCE,
            NodeType.PLAYER0,
            NodeType.PLAYER1,
            NodeType.PLAYER0,
            NodeType.PLAYER1,
            NodeType.PLAYER0,
            NodeType.PLAYER1,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
            NodeType.TERMINAL,
        ),
        first_child=(0, 6, 8, 10, 12, 14, 16, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18),
        child_count=(6, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
        children=(
            ChildLink(child=NodeId(1), chance_prob=1 / 6),
            ChildLink(child=NodeId(2), chance_prob=1 / 6),
            ChildLink(child=NodeId(3), chance_prob=1 / 6),
            ChildLink(child=NodeId(4), chance_prob=1 / 6),
            ChildLink(child=NodeId(5), chance_prob=1 / 6),
            ChildLink(child=NodeId(6), chance_prob=1 / 6),
            ChildLink(child=NodeId(7)),
            ChildLink(child=NodeId(8)),
            ChildLink(child=NodeId(9)),
            ChildLink(child=NodeId(10)),
            ChildLink(child=NodeId(11)),
            ChildLink(child=NodeId(12)),
            ChildLink(child=NodeId(13)),
            ChildLink(child=NodeId(14)),
            ChildLink(child=NodeId(15)),
            ChildLink(child=NodeId(16)),
            ChildLink(child=NodeId(17)),
            ChildLink(child=NodeId(18)),
            ChildLink(child=NodeId(19)),
            ChildLink(child=NodeId(20)),
            ChildLink(child=NodeId(21)),
            ChildLink(child=NodeId(22)),
        ),
        infoset_ids=(
            None,
            InfosetId(0),
            InfosetId(1),
            InfosetId(2),
            InfosetId(3),
            InfosetId(4),
            InfosetId(5),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        terminal_payoffs=(
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Chips(1),
            Chips(-1),
            Chips(2),
            Chips(-2),
            Chips(3),
            Chips(-3),
            Chips(4),
            Chips(-4),
            Chips(5),
            Chips(-5),
            Chips(6),
            Chips(-6),
            Chips(7),
            Chips(-7),
            Chips(8),
            Chips(-8),
        ),
    )
